#!/bin/bash

# Get battery information using upower
battery_info=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)

# Extract relevant information
percentage=$(grep -E "percentage" <<< "$battery_info" | awk '{print $2}' | tr -d '%')
state=$(grep -E "state" <<< "$battery_info" | awk '{print $2}')
time_to_full=$(grep -E "time to full" <<< "$battery_info" | awk '{print $4 " " $5}')
time_to_empty=$(grep -E "time to empty" <<< "$battery_info" | awk '{print $4 " " $5}')

# Determine the state symbol
if [ "$state" = "charging" ]; then
  state_symbol=""
elif [ "$state" = "discharging" ]; then
  if [ "$percentage" -le 10 ]; then
    state_symbol=""
  elif [ "$percentage" -le 20 ]; then
    state_symbol=""
  elif [ "$percentage" -le 30 ]; then
    state_symbol=""
  elif [ "$percentage" -le 40 ]; then
    state_symbol=""
  elif [ "$percentage" -le 50 ]; then
    state_symbol=""
  elif [ "$percentage" -le 60 ]; then
    state_symbol=""
  elif [ "$percentage" -le 70 ]; then
    state_symbol=""
  elif [ "$percentage" -le 80 ]; then
    state_symbol=""
  elif [ "$percentage" -le 90 ]; then
    state_symbol=""
  else
    state_symbol=""
  fi
else
  state_symbol="o"
fi

# Determine whether to display time to empty or time to full
if [ "$state" = "charging" ]; then
  time_info="$time_to_full"
elif [ "$state" = "discharging" ]; then
  time_info="$time_to_empty"
else
  time_info="e"
fi

# Display battery information
echo "$state_symbol  $percentage% ($time_info)"
